from pathlib import Path

from docxtpl import DocxTemplate
from spire.doc import Document, FileFormat
from docx import Document as Doc

from config import (
    OUTPUT_PATH,
    TEMPORARY_PATH,
    QUESTIONS_PATH,
    COVER_TEMPLATE,
    TEMPLATE_TITLE_STRING,
    TEMPLATE_ABBREVIATION_STRING,
)
from models import EmployeeData, SubjectData


def create_output_document_path(subject: SubjectData, employee: EmployeeData) -> Path:
    """Create a file path for a test document."""
    subject_abbrev = subject["abbreviation"]
    employee_name = employee["name"]
    employee_license = employee["license"]

    folder_path = OUTPUT_PATH / f"{employee_name} {employee_license}"
    folder_path.mkdir(parents=True, exist_ok=True)

    file_name = f"{employee_name} {employee_license} {subject_abbrev.upper()}.docx"

    return folder_path / file_name


def create_cover_page(subject: SubjectData) -> Path:
    """Create cover page and return temporary file path."""
    cover_page = DocxTemplate(COVER_TEMPLATE)
    context = {
        TEMPLATE_TITLE_STRING: subject["title"],
        TEMPLATE_ABBREVIATION_STRING: subject["abbreviation"],
    }
    cover_page.render(context)

    temp_file = TEMPORARY_PATH / f"cover-{subject['abbreviation']}.docx"
    temp_file.parent.mkdir(parents=True, exist_ok=True)
    cover_page.save(str(temp_file))

    return temp_file


def generate_test_for_subject(subject: SubjectData, employee: EmployeeData) -> Path:
    """Merge cover page with selected question files."""
    subject_abbrev = subject["abbreviation"]

    # Get output test file path
    output_file_path = create_output_document_path(subject, employee)

    # Create cover page
    cover_page_path = create_cover_page(subject)

    # Create question file names from generated numbers
    question_numbers = subject["generated_numbers"]
    question_files = [
        f"{QUESTIONS_PATH}/{subject_abbrev}/{number}.docx"
        for number in question_numbers
    ]

    # Create test document
    test_document = Document()
    test_document.LoadFromFile(str(cover_page_path))

    # Merge question files
    for i, question_file in enumerate(question_files):
        # Load a question
        question = Document()
        question.LoadFromFile(str(question_file))

        # Get the last section of the test file and
        # add question after it
        lastSection = test_document.Sections.get_Item(test_document.Sections.Count - 1)

        for j in range(question.Sections.Count):
            section = question.Sections.get_Item(j)

            for k in range(section.Body.ChildObjects.Count):
                obj = section.Body.ChildObjects.get_Item(k)

                # Add question number at the beginning
                if k == 0:
                    obj.Text = f"{i+1}. {obj.Text}"
                lastSection.Body.ChildObjects.Add(obj.Clone())

        question.Close()

    # Save file compatible with Word 2016
    test_document.SaveToFile(str(output_file_path), FileFormat.Docx2016)
    test_document.Close()

    # Delete watermark from the top of the document generated by Spire.Doc
    test_document = Doc(str(output_file_path))
    test_document.paragraphs[0].clear()
    test_document.save(output_file_path)

    return output_file_path


def generate_all_tests(
    subjects: list[SubjectData], employee: EmployeeData
) -> list[Path]:
    """Generate tests for all subjects and return list of output file paths."""
    output_paths: list[Path] = []

    for subject in subjects:
        output_path = generate_test_for_subject(subject, employee)
        output_paths.append(output_path)

    return output_paths
